moviefun:
    datasources:
      movies:
        url: jdbc:mysql://localhost:3306/movies?useSSL=false
        username: root
        password: Ubwani11
      albums:
        url: jdbc:mysql://localhost:3306/albums?useSSL=false
        username: root
        password: Ubwani11
spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
